local_sources:
  - .
  - Samples/SplitScreenContainer
  - Samples/BackStackContainer
  - Samples/ModalContainer
  - Samples/AlertContainer

platforms:
  - ios
podspec_paths:
  - Development.podspec

external_source_pods:
  - MarketWorkflowUI:
    - :git: 'https://github.com/squareup/market.git'
      :tag: 'ios/MarketWorkflowUI/80.0.0'
